### ISSUE TITLE
Snowflakes freeze when page loading is taking too long

### ISSUE THREAD

**Issue by minusQuantumNeko** [Osekai/osekai#114]
They don't fall and only move left and right until page is loaded

**Comment by Tanza3D** [comment]
can you get an example of this somewhere?

**Comment by minusQuantumNeko** [comment]
> can you get an example of this somewhere?


https://user-images.githubusercontent.com/43725099/205515640-cd4e54fa-f254-4ca9-8e89-30a295214166.mp4

**Comment by Tanza3D** [comment]
can't fix that, it's something inherent to css i think. there's nothing im doing which would cause that, all the animations are through CSS

**Comment by minusQuantumNeko** [comment]
:pain:
