### ISSUE TITLE
Server respond with 404 for some images in Osekai Badges

### ISSUE THREAD

**Issue by Yukinyaaa** [Osekai/osekai#174]
https://osekai.net/badges/
![image](https://user-images.githubusercontent.com/65931718/208109917-a40b7fe0-030c-4dc4-a9ab-aa63a8876b4d.png)
![image](https://user-images.githubusercontent.com/65931718/208109939-5a096154-36c0-4ee3-8a04-22d00951ac3f.png)

meow

**Comment by Tanza3D** [comment]
this is not our fault, osu! refuses to load so many images at once. make sure you're using @1x and not @2x

**Comment by Yukinyaaa** [comment]
Any thoughts on splitting it into pages?

**Comment by Tanza3D** [comment]
would prefer not to but might be worth looking into
