### ISSUE TITLE
Mobile comments design weirdness

### ISSUE THREAD

**Issue by minusQuantumNeko** [Osekai/osekai#22]
It's really hard to tell how many upvotes comment you upvoted has, and if the button is active even when you are using mobile!
![image](https://user-images.githubusercontent.com/43725099/204279925-4699afe0-6a94-41df-90f4-d0202fd75fd1.png)
![image](https://user-images.githubusercontent.com/43725099/204279944-22ac33d7-a857-45d6-a50e-cdaa5213cb3f.png)

**Comment by Tanza3D** [comment]
this needs a redesign
