### ISSUE TITLE
Osekai does a 301 redirect for no reason

### ISSUE THREAD

**Issue by Tanza3D** [Osekai/osekai#300]
no clue why this is happening, but when you visit snapshots, it immediately redirects you (to add the /)
https://osekai.net/snapshots?version=86
![image](https://github.com/Osekai/osekai/assets/33783503/5a94e181-9e07-448e-a5cf-41fedcf6c8d1)
same thing applies for medals, this makes google not happy
![image](https://github.com/Osekai/osekai/assets/33783503/0197d237-4579-4b5d-9ba0-3231ae94a690)
seems pages which can't be indexed do get indexed anyway based on their redirect, but it'd still be better to not have this issue imo
![image](https://github.com/Osekai/osekai/assets/33783503/e9a23668-d601-4e5a-be14-4628da0f0d38)
![image](https://github.com/Osekai/osekai/assets/33783503/80010485-0e89-4555-bcd9-380b1c278d9d)
![image](https://github.com/Osekai/osekai/assets/33783503/52dbcc00-18f5-47cb-b036-57a9a23b1516)

**Comment by Tanza3D** [comment]
doesn't seem to be something we can fix

**Comment by Coppertine** [comment]
Could be something with how the redirect part of the router would work

**Comment by Tanza3D** [comment]
this isn't just on the router, this is on all pages, and it does it with the htaccess completely removed as well. as i say i dont think we can fix it

**Comment by Coppertine** [comment]
What's weird is that it also happens locally.
