### ISSUE TITLE
"Drum & Bass Pack" medal breaks the user banner

### ISSUE THREAD

**Issue by PillTime** [Osekai/osekai#311]
I'm guessing the ampersand should be replaced with `&amp;`
![Screenshot 2023-06-17 235455](https://github.com/Osekai/osekai/assets/2399664/901dbce8-50d3-4306-bea4-c9adc07795aa)

**Comment by Coppertine** [comment]
someone forgot to encode the URI...

**Comment by minusQuantumNeko** [comment]
@Tanza3D

**Comment by Tanza3D** [comment]
i will fix it soon :3
