### ISSUE TITLE
User banner not loading.

### ISSUE THREAD

**Issue by Ladwick** [Osekai/osekai#357]
The title is pretty self explanatory, I have tried changing all the styles of the banner, even the colors, logging out and back in the website and entering from multiple browsers but nothing will work, the banner will be displayed in blank like this:
![image](https://github.com/Osekai/osekai/assets/37979533/c9127f72-2648-42f3-8181-b3c890ac860c)

After checking a little the code of the banner, I got to its URL and it... exist, but I don't understand what's happening here aside from the fact that the error is called 'no name', like if it can't fetch a specific piece of metadata from my account, but then the info of pp, medals, ranks, etc is correct.
![image](https://github.com/Osekai/osekai/assets/37979533/e5a3dbf9-9a6d-40a8-b2f5-b2d2cb46a181)

**Comment by Tanza3D** [comment]
could you check this again?

**Comment by Ladwick** [comment]
Sorry, I forgot to close this issue, you already fixed it

**Comment by Tanza3D** [comment]
no worries ty just checking
