### ISSUE TITLE
When opened osekai profile with an invalid user name, nothing will appear on the page

### ISSUE THREAD

**Issue by yuzupon1133** [Osekai/osekai#89]
https://osekai.net/profiles/?user=wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
![image](https://user-images.githubusercontent.com/65931718/205375965-dfddea4e-dcf7-48fe-9306-81f33a19d9e0.png)

**Comment by yuzupon1133** [comment]
https://osekai.net/rankings/?ranking=wwwww&type=Users
![image](https://user-images.githubusercontent.com/65931718/205376972-7c9bae15-9659-4fff-8b31-7b6378215e56.png)

**Comment by yuzupon1133** [comment]
https://osekai.net/badges/?badge=999999
![image](https://user-images.githubusercontent.com/65931718/205377406-5cbec880-1020-4c1b-a56e-839761abf239.png)
sorry hubz🥲

**Comment by yuzupon1133** [comment]
When adding an invalid user in Osekai Rankings, the server returns a 500 error.
So you will not get a message such as "Could not add because of invalid user name".
![image](https://user-images.githubusercontent.com/65931718/205445618-af17df17-6180-4eea-8169-8a22c5cbfc1b.png)

**Comment by Tanza3D** [comment]
please make a new issue for that

**Comment by yuzupon1133** [comment]
okay!
